[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip",
    ". /opt/venv/bin/activate && pip install -r backend/requirements-essential.txt"
]

[phases.build]
cmds = [
    "echo 'Backend dependencies installed'",
    ". /opt/venv/bin/activate && python -c 'import fastapi, uvicorn; print(\"Core dependencies verified\")'"
]

[start]
cmd = ". /opt/venv/bin/activate && python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT --workers 1"

