[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
    "echo 'Starting installation phase - $(date)'",
    "python --version",
    "which pip && echo 'pip found at:' && which pip",
    "pip install --upgrade pip --break-system-packages",
    "pip install -r backend/requirements-essential.txt --break-system-packages"
]

[phases.build]
cmds = [
    "echo 'Build phase - backend dependencies installed (v2.0 - standalone pip)'",
    "python -c 'import fastapi, uvicorn; print(\"Core dependencies verified\")'"
]

[start]
cmd = "cd backend && (uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1 || python -m uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1)"

