[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "curl"]

[phases.install]
cmds = [
    "python --version",
    "python -c 'import sys; print(sys.executable)'",
    "which pip || curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python get-pip.py",
    "python -m pip install --upgrade pip",
    "python -m pip install -r backend/requirements-essential.txt"
]

[phases.build]
cmds = [
    "echo 'Build phase - backend dependencies installed'",
    "python -c 'import fastapi, uvicorn; print(\"Core dependencies verified\")'"
]

[start]
cmd = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1"

