[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "python -m pip install -r backend/requirements-essential.txt"
]

[phases.build]
cmds = [
    "echo 'Build phase - backend dependencies installed'"
]

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"

