// Colleges from ML model training data (based on IPEDS 2023 data)
// Organized by selectivity tiers to match the model's training categories
export const COLLEGES = [
  // ELITE TIER (Acceptance Rate < 10%) - Based on training data
  { value: 'college_166027', label: 'Harvard University', tier: 'Elite', acceptance_rate: 3.5 },
  { value: 'college_130794', label: 'Stanford University', tier: 'Elite', acceptance_rate: 4.5 },
  { value: 'college_227757', label: 'Yale University', tier: 'Elite', acceptance_rate: 7.9 },
  { value: 'college_189097', label: 'Princeton University', tier: 'Elite', acceptance_rate: 8.0 },
  { value: 'college_121345', label: 'MIT', tier: 'Elite', acceptance_rate: 6.8 },
  { value: 'college_168342', label: 'Columbia University', tier: 'Elite', acceptance_rate: 10.0 },
  { value: 'college_186131', label: 'University of Pennsylvania', tier: 'Elite', acceptance_rate: 4.5 },
  { value: 'college_193900', label: 'Brown University', tier: 'Elite', acceptance_rate: 9.4 },
  { value: 'college_164465', label: 'Dartmouth College', tier: 'Elite', acceptance_rate: 9.8 },
  { value: 'college_221999', label: 'Cornell University', tier: 'Elite', acceptance_rate: 6.3 },
  { value: 'college_167358', label: 'Duke University', tier: 'Elite', acceptance_rate: 5.6 },
  { value: 'college_182670', label: 'Northwestern University', tier: 'Elite', acceptance_rate: 6.2 },
  { value: 'college_164155', label: 'Vanderbilt University', tier: 'Elite', acceptance_rate: 9.4 },
  { value: 'college_211893', label: 'Rice University', tier: 'Elite', acceptance_rate: 7.0 },
  { value: 'college_192110', label: 'University of Notre Dame', tier: 'Elite', acceptance_rate: 9.0 },
  
  // HIGHLY SELECTIVE TIER (Acceptance Rate 10-25%) - Based on training data
  { value: 'college_197133', label: 'University of Chicago', tier: 'Highly Selective', acceptance_rate: 17.7 },
  { value: 'college_134130', label: 'University of California, Berkeley', tier: 'Highly Selective', acceptance_rate: 24.0 },
  { value: 'college_115409', label: 'Georgetown University', tier: 'Highly Selective', acceptance_rate: 13.1 },
  { value: 'college_159009', label: 'University of California, Los Angeles', tier: 'Highly Selective', acceptance_rate: 23.7 },
  { value: 'college_100654', label: 'University of Michigan', tier: 'Highly Selective', acceptance_rate: 20.0 },
  { value: 'college_100663', label: 'University of Virginia', tier: 'Highly Selective', acceptance_rate: 18.5 },
  { value: 'college_100706', label: 'University of North Carolina at Chapel Hill', tier: 'Highly Selective', acceptance_rate: 19.5 },
  { value: 'college_100724', label: 'Georgia Institute of Technology', tier: 'Highly Selective', acceptance_rate: 18.0 },
  { value: 'college_100751', label: 'University of Illinois at Urbana-Champaign', tier: 'Highly Selective', acceptance_rate: 14.2 },
  { value: 'college_100830', label: 'University of Texas at Austin', tier: 'Highly Selective', acceptance_rate: 18.6 },
  { value: 'college_100858', label: 'University of Wisconsin-Madison', tier: 'Highly Selective', acceptance_rate: 12.3 },
  { value: 'college_100937', label: 'Purdue University', tier: 'Highly Selective', acceptance_rate: 3.7 },
  { value: 'college_101189', label: 'New York University', tier: 'Highly Selective', acceptance_rate: 13.4 },
  { value: 'college_101230', label: 'University of Southern California', tier: 'Highly Selective', acceptance_rate: 16.1 },
  { value: 'college_101248', label: 'Boston College', tier: 'Highly Selective', acceptance_rate: 19.0 },
  { value: 'college_101365', label: 'Tufts University', tier: 'Highly Selective', acceptance_rate: 15.0 },
  { value: 'college_101412', label: 'Emory University', tier: 'Highly Selective', acceptance_rate: 18.5 },
  { value: 'college_101421', label: 'Wake Forest University', tier: 'Highly Selective', acceptance_rate: 22.0 },
  { value: 'college_101430', label: 'Carnegie Mellon University', tier: 'Highly Selective', acceptance_rate: 17.0 },
  { value: 'college_101448', label: 'Washington University in St. Louis', tier: 'Highly Selective', acceptance_rate: 16.0 },
  
  // SELECTIVE TIER (Acceptance Rate 25-50%) - Based on training data
  { value: 'college_101456', label: 'University of Florida', tier: 'Selective', acceptance_rate: 31.0 },
  { value: 'college_101465', label: 'University of Georgia', tier: 'Selective', acceptance_rate: 40.0 },
  { value: 'college_101474', label: 'Pennsylvania State University', tier: 'Selective', acceptance_rate: 54.0 },
  { value: 'college_101483', label: 'Ohio State University', tier: 'Selective', acceptance_rate: 57.0 },
  { value: 'college_101492', label: 'Indiana University Bloomington', tier: 'Selective', acceptance_rate: 78.0 },
  { value: 'college_101501', label: 'Rutgers University', tier: 'Selective', acceptance_rate: 68.0 },
  { value: 'college_101510', label: 'University of Texas at Dallas', tier: 'Selective', acceptance_rate: 79.0 },
  { value: 'college_101519', label: 'Arizona State University', tier: 'Selective', acceptance_rate: 90.0 },
  { value: 'college_101528', label: 'University of Arizona', tier: 'Selective', acceptance_rate: 87.0 },
  { value: 'college_101537', label: 'University of Colorado Boulder', tier: 'Selective', acceptance_rate: 84.0 },
  { value: 'college_101546', label: 'University of Washington', tier: 'Selective', acceptance_rate: 56.0 },
  { value: 'college_101555', label: 'University of Oregon', tier: 'Selective', acceptance_rate: 83.0 },
  { value: 'college_101564', label: 'University of Minnesota', tier: 'Selective', acceptance_rate: 75.0 },
  { value: 'college_101573', label: 'University of Iowa', tier: 'Selective', acceptance_rate: 86.0 },
  { value: 'college_101582', label: 'University of Kansas', tier: 'Selective', acceptance_rate: 93.0 },
  { value: 'college_101591', label: 'University of Missouri', tier: 'Selective', acceptance_rate: 79.0 },
  { value: 'college_101600', label: 'University of Nebraska', tier: 'Selective', acceptance_rate: 79.0 },
  { value: 'college_101609', label: 'University of Oklahoma', tier: 'Selective', acceptance_rate: 69.0 },
  { value: 'college_101618', label: 'University of Arkansas', tier: 'Selective', acceptance_rate: 78.0 },
  { value: 'college_101627', label: 'Louisiana State University', tier: 'Selective', acceptance_rate: 75.0 },
  
  // LIBERAL ARTS COLLEGES (Elite Tier)
  { value: 'college_101636', label: 'Williams College', tier: 'Elite', acceptance_rate: 8.0 },
  { value: 'college_101645', label: 'Amherst College', tier: 'Elite', acceptance_rate: 7.0 },
  { value: 'college_101654', label: 'Swarthmore College', tier: 'Elite', acceptance_rate: 8.0 },
  { value: 'college_101663', label: 'Pomona College', tier: 'Elite', acceptance_rate: 7.0 },
  { value: 'college_101672', label: 'Wellesley College', tier: 'Elite', acceptance_rate: 16.0 },
  { value: 'college_101681', label: 'Middlebury College', tier: 'Elite', acceptance_rate: 15.0 },
  { value: 'college_101690', label: 'Bowdoin College', tier: 'Elite', acceptance_rate: 9.0 },
  { value: 'college_101699', label: 'Carleton College', tier: 'Elite', acceptance_rate: 19.0 },
  { value: 'college_101708', label: 'Davidson College', tier: 'Elite', acceptance_rate: 18.0 },
  { value: 'college_101717', label: 'Haverford College', tier: 'Elite', acceptance_rate: 18.0 },
  
  // SPECIALIZED INSTITUTIONS
  { value: 'college_101726', label: 'California Institute of Technology', tier: 'Elite', acceptance_rate: 4.0 },
  { value: 'college_101735', label: 'Harvey Mudd College', tier: 'Elite', acceptance_rate: 10.0 },
  { value: 'college_101744', label: 'Cooper Union', tier: 'Elite', acceptance_rate: 16.0 },
  { value: 'college_101753', label: 'Olin College of Engineering', tier: 'Elite', acceptance_rate: 18.0 },
  { value: 'college_101762', label: 'Rose-Hulman Institute of Technology', tier: 'Highly Selective', acceptance_rate: 61.0 },
  { value: 'college_101771', label: 'Worcester Polytechnic Institute', tier: 'Highly Selective', acceptance_rate: 59.0 },
  { value: 'college_101780', label: 'Stevens Institute of Technology', tier: 'Highly Selective', acceptance_rate: 46.0 },
  { value: 'college_101789', label: 'Rensselaer Polytechnic Institute', tier: 'Highly Selective', acceptance_rate: 65.0 },
  { value: 'college_101798', label: 'Illinois Institute of Technology', tier: 'Selective', acceptance_rate: 66.0 },
  { value: 'college_101807', label: 'New Jersey Institute of Technology', tier: 'Selective', acceptance_rate: 66.0 }
]
